-- auto-generated definition
create table tb_food
(
    id            bigint generated by default as identity
        constraint tb_food_pkey
            primary key,
    description   varchar(255),
    restaurant_id bigint
        constraint fk_tb_food_tb_restaurant
            references tb_restaurant,
    name          varchar(255),
    price         numeric(19, 2)
);

-- auto-generated definition
create table tb_restaurant_tb_food
(
    restaurant_id bigint not null
        constraint fk_tb_restaurant_tb_food_tb_restaurant
            references tb_restaurant,
    foods_id      bigint not null
        constraint uk_foods
            unique
        constraint fk_tb_restaurant_tb_food_tb_food
            references tb_food
);

