-- auto-generated definition
create table tb_restaurant
(
    id          bigint generated by default as identity
        constraint tb_restaurant_pkey
            primary key,
    cnpj        varchar(255),
    createdat   timestamp,
    name        varchar(255),
    owner       varchar(255),
    updatedat   timestamp,
    location_id bigint
        constraint fk_tb_restaurant_tb_location
            references tb_location
);

