package com.camilo.myifood.models

import com.camilo.myifood.dto.FoodDTO
import io.smallrye.mutiny.Multi
import io.vertx.mutiny.pgclient.PgPool
import java.math.BigDecimal
import java.util.stream.StreamSupport

data class Food(
    val id: Long? = null,
    val name: String? = null,
    val description: String? = null,
    val restaurant: Restaurant? = null,
    val price: BigDecimal? = null,
    val idRestaurant: Long? = null
) {
    companion object {
        /*
        	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	description varchar(200) NULL,
	name varchar(50) NULL,
	price numeric(19,2) NOT NULL,
	restaurant_id int8 NOT NULL
         */
        fun findAll(pgPool: PgPool): Multi<FoodDTO> =
            pgPool.preparedQuery("select id, description, name, price, restaurant_id from food ").execute()
                .onItem().transformToMulti { rowSet ->
                    Multi.createFrom().items {
                        StreamSupport.stream(rowSet.spliterator(), false)
                    }
                }
                .onItem().transform { FoodDTO.from(it) }


    }
}
